name: ReportGenerator

on:
  workflow_call

jobs:
  ReportGenerator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4
      
      - name: Check for global.json
        id: check-global-json
        run: |
          if [ -f global.json ]; then
            echo "global_json_exists=true" >> $GITHUB_ENV
          else
            echo "global_json_exists=false" >> $GITHUB_ENV
          fi

      - name: 🔧 Setup .NET SDK
        if: env.global_json_exists == 'true'
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json 
    
      - name: Setup .NET without global.json
        if: env.global_json_exists == 'false'
        uses: actions/setup-dotnet@v4

      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          name: test-results
          path: artifacts/test-results
          
      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@5.1.22
        with:
          reports: artifacts/test-results/**/TestResults/**/coverage.cobertura.xml
          targetdir: Coverage
          reporttypes: Html
          
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: Coverage/
          retention-days: 1
