name: Documentation

on:
  workflow_call:
    inputs:
      REPOSITORY_NAME:
        required: true
        type: string

jobs:
  Documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: nuget/setup-nuget@v1
        with:
          nuget-version: latest

      - name: Build Documentation
        uses: nunit/docfx-action@v2.4.0  
        with:
          args: docs/docfx.json

      - name: Upload documentation results
        uses: actions/upload-artifact@v2
        with:
          name: ${{inputs.REPOSITORY_NAME}}-documentation
          path: docs/_site
          retention-days: 2